version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.4
    volumes:
      - ./loki:/etc/loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_CONFIG=/var/lib/grafana/grafana.ini
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - loki