server {
    server_name loki.eniemela.fi;
    listen 3110 ssl default_server;
    listen [::]:3110 ssl default_server;

    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    ssl_protocols TLSv1.3;
    # cd /etc/ssl && openssl req -nodes -x509 -new -keyout private/nginx-selfsigned.key -out certs/nginx-selfsigned.crt -days 3650
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3100;
    }
}
